use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use sqlx::{AnyPool, Error};

use crate::configs::database::DatabaseScheme;

use super::Builder;

#[derive(sqlx::FromRow, Clone, Deserialize, Serialize)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub password: String,
}

pub struct UserBuilder;

#[async_trait]
impl Builder for UserBuilder {
    async fn build(db_scheme: &DatabaseScheme, pool: &AnyPool) -> Result<(), Error> {
        let id_type = match db_scheme {
            DatabaseScheme::POSTGRES => "INT GENERATED BY DEFAULT AS IDENTITY",
            DatabaseScheme::SQLITE => "INTEGER PRIMARY KEY AUTOINCREMENT",
            DatabaseScheme::MYSQL => "INT AUTO_INCREMENT PRIMARY KEY",
        };

        let statement = format!(
            r#"
            CREATE TABLE IF NOT EXISTS users (
                id {id_type},
                username VARCHAR(255),
                email VARCHAR(255),
                password VARCHAR(255)
            );
            "#);

        sqlx::query(&statement).execute(pool).await?;

        Ok(())
    }
}