[server]
host = "127.0.0.1"
port = 8080

[logger]
level = "debug"

[database]
clean_start = true
url = "sqlite:file:smarinth?mode=memory&cache=shared"

[control]
embed = true
client_id = "client-smarinth"
host = "127.0.0.1"
port = 1883

[auth]
secret = "smarinth-secret"
expiration = 233333