[server]
host = "127.0.0.1"
port = 8080

[logger]
level = "debug"

[database]
url = "sqlite::memory:"

[control]
embed = true
client_id = "client-smarinth"
host = "127.0.0.1"
port = 1883

[auth]
secret = "smarinth-secret"
expiration = 233333